# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../../training/"
path_to_session_files: "../../training/session/"
path_to_models: "../../training/models/"
recording_height: 120
recording_width: 180
recording_fps: 20
frame_height: 40
frame_width: 60
# Procedural flags
control_mode: full_model  # modes: full_model, shared, full_expert
m_length: 4 # memory length
m_interval: 1 # memory interval

# Model wrapper
pretrained_start: true  # should load model from file or nah
prediction_mode: steer  # modes: supervisor, steer, steer_diff

dagger_training_enabled: false
dagger_epoch_size: 3000
dagger_epochs_count: 6