# Constant properties
window_width: 960
window_height: 480
path_to_training: "../training/"
path_to_models: "../training/models/"
recording_height: 40
recording_width: 60
recording_fps: 20
# Procedural flags
car_override_enabled: true
recording_enabled: false
aggregated_recording_enabled: true
