# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../../training/"
path_to_session_files: "../../training/session/"
path_to_models: "../../training/models/"
path_to_dagger_models: "../../training/dagger_models/"
recording_height: 120
recording_width: 180
recording_fps: 20
frame_height: 50
frame_width: 180
# Procedural flags
control_mode: full_model  # modes: full_model, shared, full_expert
m_length: 1 # memory length
m_interval: 1 # memory interval

# Model wrapper
model_start_mode: regular  # modes: regular, dagger, clean
model_num: 15

# Imitation learning
dagger_training_enabled: false
dagger_epoch_size: 1000
dagger_epochs_count: 16
dagger_model: model_n1_m1_15.h5