# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../../training/"
path_to_models: "../../training/models/"
recording_height: 120
recording_width: 180
recording_fps: 20
frame_height: 40
frame_width: 60
# Procedural flags
# modes: full_model, shared, full_expert
prediction_mode: full_expert

dagger_training_enabled: false
dagger_epoch_size: 3000
dagger_epochs_count: 6