# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../../training/"
path_to_session_files: "../../training/session/"
path_to_models: "../../training/models/"
recording_height: 120
recording_width: 180
recording_fps: 20
frame_height: 50
frame_width: 180
# Procedural flags
control_mode: shared  # modes: full_model, shared, full_expert
m_length: 1 # memory length
m_interval: 1 # memory interval

# Model wrapper
pretrained_start: false  # should load model from file or nah
model_num: 8

dagger_training_enabled: true
dagger_epoch_size: 2000
dagger_epochs_count: 16