# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../../training/"
path_to_models: "../../training/models/"
recording_height: 40
recording_width: 60
recording_fps: 20
# Procedural flags
recording_enabled: false
expert_supervision_enabled: true
# DAGGER
dagger_iter_max: 10
dagger_batch_size: 2000
